// Poster URLs are fetched dynamically from /api/tmdb/movie/[id] on mount.
// This ensures we always get current, valid TMDB CDN paths.

export const STAR_WARS_SEED = [
  { upc: "024543246558", title: "Star Wars: Episode I – The Phantom Menace", year: 1999, format: "DVD", director: "George Lucas", runtime: 136, genre: "Sci-Fi", rating: "PG", synopsis: "Jedi Knights Qui-Gon Jinn and Obi-Wan Kenobi discover young Anakin Skywalker on Tatooine while protecting Queen Amidala from the Trade Federation's blockade of Naboo.", cast: "Liam Neeson, Ewan McGregor, Natalie Portman", poster_url: "", collection: "Prequel Trilogy", tmdb_id: 1893 },
  { upc: "024543246565", title: "Star Wars: Episode II – Attack of the Clones", year: 2002, format: "DVD", director: "George Lucas", runtime: 142, genre: "Sci-Fi", rating: "PG", synopsis: "Anakin Skywalker and Padmé Amidala fall in love while Obi-Wan uncovers a secret clone army, setting the stage for the devastating Clone Wars.", cast: "Ewan McGregor, Natalie Portman, Hayden Christensen", poster_url: "", collection: "Prequel Trilogy", tmdb_id: 1894 },
  { upc: "024543246572", title: "Star Wars: Episode III – Revenge of the Sith", year: 2005, format: "DVD", director: "George Lucas", runtime: 140, genre: "Sci-Fi", rating: "PG-13", synopsis: "Anakin Skywalker's fall to the dark side is complete as he becomes Darth Vader, the Jedi Order is destroyed, and the Galactic Empire rises to power.", cast: "Ewan McGregor, Natalie Portman, Hayden Christensen", poster_url: "", collection: "Prequel Trilogy", tmdb_id: 1895 },
  { upc: "024543513568", title: "Star Wars: Episode IV – A New Hope", year: 1977, format: "DVD", director: "George Lucas", runtime: 121, genre: "Sci-Fi", rating: "PG", synopsis: "Farm boy Luke Skywalker joins forces with a Jedi Knight, a smuggler, a Wookiee, and two droids to rescue Princess Leia and save the galaxy from the Empire's Death Star.", cast: "Mark Hamill, Harrison Ford, Carrie Fisher", poster_url: "", collection: "Original Trilogy", tmdb_id: 11 },
  { upc: "024543513575", title: "Star Wars: Episode V – The Empire Strikes Back", year: 1980, format: "DVD", director: "Irvin Kershner", runtime: 124, genre: "Sci-Fi", rating: "PG", synopsis: "The rebels face devastating losses as Darth Vader pursues Luke Skywalker, who trains with Jedi Master Yoda on Dagobah and discovers a shocking truth about his father.", cast: "Mark Hamill, Harrison Ford, Carrie Fisher", poster_url: "", collection: "Original Trilogy", tmdb_id: 1891 },
  { upc: "024543513582", title: "Star Wars: Episode VI – Return of the Jedi", year: 1983, format: "DVD", director: "Richard Marquand", runtime: 131, genre: "Sci-Fi", rating: "PG", synopsis: "Luke Skywalker confronts Darth Vader and the Emperor in a final battle while the rebel fleet launches a desperate attack on the second Death Star orbiting Endor.", cast: "Mark Hamill, Harrison Ford, Carrie Fisher", poster_url: "", collection: "Original Trilogy", tmdb_id: 1892 },
  { upc: "786936853742", title: "Star Wars: The Force Awakens", year: 2015, format: "Blu-ray", director: "J.J. Abrams", runtime: 138, genre: "Sci-Fi", rating: "PG-13", synopsis: "A scavenger named Rey, a rogue stormtrooper, and a daring pilot join forces with Han Solo and Chewbacca to battle the sinister First Order and its dark warrior Kylo Ren.", cast: "Daisy Ridley, John Boyega, Adam Driver", poster_url: "", collection: "Sequel Trilogy", tmdb_id: 140607 },
  { upc: "786936854329", title: "Star Wars: The Last Jedi", year: 2017, format: "Blu-ray", director: "Rian Johnson", runtime: 152, genre: "Sci-Fi", rating: "PG-13", synopsis: "Rey seeks Luke Skywalker's help to turn the tide against the First Order while the Resistance faces a desperate evacuation under relentless pursuit.", cast: "Mark Hamill, Daisy Ridley, Adam Driver", poster_url: "", collection: "Sequel Trilogy", tmdb_id: 181808 },
  { upc: "786936863109", title: "Star Wars: The Rise of Skywalker", year: 2019, format: "Blu-ray", director: "J.J. Abrams", runtime: 142, genre: "Sci-Fi", rating: "PG-13", synopsis: "The surviving Resistance faces the First Order once more as Rey, Finn, and Poe carry out a final mission to confront the resurrected Emperor Palpatine.", cast: "Daisy Ridley, Adam Driver, John Boyega", poster_url: "", collection: "Sequel Trilogy", tmdb_id: 181812 },
  { upc: "024543940012", title: "Rogue One: A Star Wars Story", year: 2016, format: "Blu-ray", director: "Gareth Edwards", runtime: 133, genre: "Sci-Fi", rating: "PG-13", synopsis: "A band of rebels embark on a desperate mission to steal the plans for the Death Star, the Empire's ultimate weapon of destruction.", cast: "Felicity Jones, Diego Luna, Ben Mendelsohn", poster_url: "", collection: "Anthology", tmdb_id: 330459 },
  { upc: "786936860290", title: "Solo: A Star Wars Story", year: 2018, format: "Blu-ray", director: "Ron Howard", runtime: 135, genre: "Sci-Fi", rating: "PG-13", synopsis: "A young Han Solo meets his future copilot Chewbacca and encounters Lando Calrissian during a series of daring escapades in the criminal underworld.", cast: "Alden Ehrenreich, Woody Harrelson, Emilia Clarke", poster_url: "", collection: "Anthology", tmdb_id: 348350 },
  { upc: "024543087892", title: "Star Wars: The Clone Wars", year: 2008, format: "DVD", director: "Dave Filoni", runtime: 98, genre: "Animation", rating: "PG", synopsis: "Anakin Skywalker and his new Padawan Ahsoka Tano embark on a mission to rescue Jabba the Hutt's kidnapped son during the galaxy-spanning Clone Wars.", cast: "Matt Lanter, Ashley Eckstein, James Arnold Taylor", poster_url: "", collection: "Animated", tmdb_id: 12180 },
  { upc: "086162891847", title: "Star Wars Holiday Special", year: 1978, format: "VHS", director: "Steve Binder", runtime: 97, genre: "Sci-Fi", rating: "NR", synopsis: "Chewbacca and Han Solo attempt to make it to Kashyyyk for Life Day while the Empire interferes. Famously bizarre and never officially re-released.", cast: "Mark Hamill, Harrison Ford, Carrie Fisher", poster_url: "", collection: "Specials", tmdb_id: 74849 },
  { upc: "024543025399", title: "Star Wars Trilogy (VHS Box Set)", year: 1995, format: "VHS", director: "George Lucas", runtime: 376, genre: "Sci-Fi", rating: "PG", synopsis: "The complete original trilogy in one collectible VHS box set featuring A New Hope, The Empire Strikes Back, and Return of the Jedi.", cast: "Mark Hamill, Harrison Ford, Carrie Fisher", poster_url: "", collection: "Original Trilogy", tmdb_id: 11 },
];
